services:
  backend:
    build: ./backend
    container_name: yourtree_backend
    # Asegúrate de configurar las variables de entorno que necesita tu backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/upload:/app/upload # Para que las imágenes no se borren si reinicias el contenedor (opcional)
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: yourtree_frontend
    ports:
      - "80:80" # El contenedor nginx expone el 80, lo mapeamos al 5173 o al puerto que prefieras
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Certs (vacío OK)
    depends_on:
      - backend
    restart: unless-stopped
