services:
  backend:
    build:
      context: .
    container_name: yourtree_backend
    env_file:
      - .env
    volumes:
      - ./upload:/app/upload
    ports:
      - "3000:3000"
    restart: unless-stopped